on:
  push:
    branches:
      - website
  pull_request:
    branches:
      - website

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Tree
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install hugo

      - name: Build
        run: |
          hugo --minify
          cd public
          echo "blam.info" > CNAME

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/website'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
